#!/bin/bash
###############################
# Resource Manager Directives #
###############################
#PBS -N 12_join_de_files_051120
#PBS -S /bin/bash
#PBS -l walltime=15:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=7gb
#PBS -o 12_join_de_files_051120.log
#PBS -e 12_join_de_files_051120.err
#PBS -M mconery@uchicago.edu
#################
# Job Execution #
#################

export TMPDIR=$WORKDIR
cd $PBS_O_WORKDIR
export TEMP=$WORKDIR

module load gcc/6.2.0
module load gemma/0.97
module load plink/1.90
module load python/3.6.0
module load R/3.6.1

#Set working directory
inp_dir=/scratch/mconery/sex-specific/de_analysis

#Run script for both genders
for gender in males females; do

	#Loop through both GRM types (X-linked genes were run with both GRMs but autosomal genes were run only with auto GRM)
	#This script only collapses the autosomal genes because we had already determined that we would use only the autosomal results
	for GRM in auto; do 
		
		#Call python script to merge files
		python join_de_files.py $inp_dir $gender $GRM
		
	done
done