#PBS -S /bin/bash
#PBS -N fastqc_run_leftovers
#PBS -l nodes=1:ppn=1
#PBS -l mem=8gb
#PBS -l walltime=3:00:00
#PBS -o fastqc_run_leftovers.out
#PBS -e fastqc_run_leftovers.err

module load java-jdk/1.8.0_92
module load fastqc/0.11.5 



# Run fastqc through the symlinks located here: 
cd /group/ober-resources/users/mstein3/rna.seq.2017/symlinks_fastq
echo fastqc $FILE* -o /scratch/mstein3/rnaseq_processing2017/FastQC_output/fastqc_leftovers


# Run fastqc and output to a new directory to keep things more organized. 
#find -name '*$FILE*' | xargs fastqc * -o /scratch/mstein3/rnaseq_processing2017/FastQC_output

fastqc $FILE* -o /scratch/mstein3/rnaseq_processing2017/FastQC_output/fastqc_leftovers











