#PBS -S /bin/bash
#PBS -N MakeBai_IndivBam
#PBS -l nodes=1:ppn=1
#PBS -l mem=16gb
#PBS -l walltime=18:00:00
#PBS -o MakeBai_IndivBam.out
#PBS -e MakeBai_IndivBam.err


module load gcc/6.2.0
module load samtools

## If I just need to make .bai: 

ORIG_BAM_DIR=/group/nicolae-lab/users/mstein3/rna.seq.2017/STARhg19_May2017_bamFiles
SORTED_DIR=/group/nicolae-lab/users/mstein3/rna.seq.2017/STARhg19_IndivSortedBam

for FQ in $ORIG_BAM_DIR/*$FILE*;
do 
	# Set up output names 
	SORTED_PREFIX="$(basename $FQ)_sorted.bam"
	# Sort .bam files
	samtools sort $FQ -o $SORTED_DIR/$SORTED_PREFIX
	
	samtools index -b $SORTED_DIR/$SORTED_PREFIX

done







# If I need to sort and make .bai: 

#INPUT_DIR=/group/nicolae-lab/users/mstein3/rna.seq.2017/STARhg19_CombinedBAM
#SORTED_DIR=/group/nicolae-lab/users/mstein3/rna.seq.2017/STARhg19_CombSortedBam
#SORTED_PREFIX="$(basename $ONE)_sorted.bam"
#BAI_NAME="$(basename $ONE)_sorted.bai"


# Sort .bam files
#samtools sort $INPUT_DIR/$ONE -o $SORTED_DIR/$SORTED_PREFIX

# Index .bam files: 
# samtools index -b $SORTED_DIR/$SORTED_PREFIX 




