#PBS -S /bin/bash
#PBS -N verifyBAMID
#PBS -l nodes=1:ppn=1
#PBS -l mem=32gb
#PBS -l walltime=48:00:00
#PBS -o verifyBAMID_bestprob.out
#PBS -e verifyBAMID_bestprob.err

module load gcc/6.2.0
module load verifybamid/1.1.3

INPUT_BAM_DIR=/group/nicolae-lab/users/mstein3/rna.seq.2017/STARhg19_IndivSortedBam
OUTPUT_DIR=/group/nicolae-lab/users/mstein3/rna.seq.2017/verifyBAMID/BestVerify_ProblemSamp
OUTPUT_NAME="$(basename $ONE)_verify"


verifyBamID --vcf /group/nicolae-lab/users/mstein3/rna.seq.2017/verifyBAMID/VCFgeno_HTgx_moreSNPs_forVerifyBAM.vcf --bam $INPUT_BAM_DIR/$ONE --out $OUTPUT_DIR/$OUTPUT_NAME --smID $TWO --best --ignoreRG


# --site : If set, use only site information in the VCF and do not compare with the actual genotypes
# --self : Only compare the ID-matching individuals between the VCF and BAM file
# --best : Find the best matching individuals (.bestSM and .bestRG files will be produced). This option is substantially longer than the default option
