#!/bin/bash
###############################
# Resource Manager Directives #
###############################
#PBS -N 6_merge_eQTL_analysis_032720
#PBS -S /bin/bash
#PBS -l walltime=10:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=7gb
#PBS -o 6_merge_eQTL_analysis_032720.log
#PBS -e 6_merge_eQTL_analysis_032720.err
#PBS -M mconery@uchicago.edu
#################
# Job Execution #
#################

export TMPDIR=$WORKDIR
cd $PBS_O_WORKDIR
export TEMP=$WORKDIR

module load gcc/6.2.0
module load gemma/0.97
module load plink/1.90
module load python/3.6.0
module load R/3.4.1


#Set working directory
work_dir=/scratch/mconery/sex-specific/eQTL_analysis

#Call python script to merge files
python join_eQTL_files.py $work_dir auto

sleep 10

#Call Mashr script
Rscript Run_mashr.R

