
# ------------ qsub parameters -------------------------- #
#PBS -S /bin/bash
#PBS -N AllResultPull
#PBS -l nodes=1:ppn=1
#PBS -l mem=8gb
#PBS -l walltime=4:00:00
#PBS -o AllResultPull.out
#PBS -e AllResultPull.err

# --------------- load modules --------------#
module load gcc
module load R


# -------------- array info ----------------# 
INPUT_FILE=$FILE

# Submit Rscript for each 
while read LINE; 
do
    echo "$LINE"
	DIR_GEMMA=/scratch/mstein3/eQTL_Hutterites/Female_LPS/GemmaDir/TMMbatch
	GENE_SNP_FILE=/group/ober-resources/users/mstein3/rna.seq.2017/summary_eQTL_results/TMMBatchCor_AgeOnlyCovar/GeneSNP_List_600K_Mash_TMMBatch.txt
	echo "Rscript /group/ober-resources/users/mstein3/rna.seq.2017/eQTL_scripts/AllResultPull_geneSNP_list.R $LINE $GENE_SNP_FILE $DIR_GEMMA"
	Rscript /group/ober-resources/users/mstein3/rna.seq.2017/eQTL_scripts/AllResultPull_geneSNP_list.R $LINE $GENE_SNP_FILE $DIR_GEMMA
done < $INPUT_FILE





# What the arguments mean: 
# DIR_GEMMA: Top-level directory to store GEMMA results for each gene.
# LINE: a gene name
# GENE_SNP_FILE: a three column file with gene names and a SNP 



#	GENE_SNP_FILE=/group/ober-resources/users/mstein3/rna.seq.2017/summary_eQTL_results/TMMBatchCor_AgeOnlyCovar/GeneSNP_List_600K_Mash_TMMBatch.txt
#	DIR_GEMMA=/scratch/mstein3/eQTL_Hutterites/Male_Null/GemmaDir/TMMbatch
#	DIR_GEMMA=/scratch/mstein3/eQTL_Hutterites/Male_LPS/GemmaDir/TMMbatch
#   DIR_GEMMA=/scratch/mstein3/eQTL_Hutterites/Female_Null/GemmaDir/TMMbatch
#   DIR_GEMMA=/scratch/mstein3/eQTL_Hutterites/Female_LPS/GemmaDir/TMMbatch


